from asyncio import AbstractEventLoopPolicy, AbstractChildWatcher, AbstractEventLoop

class GLibEventLoopPolicy(AbstractEventLoopPolicy):
    def get_child_watcher(self) -> AbstractChildWatcher: ...
    def get_event_loop(self) -> AbstractEventLoop: ...
    def new_event_loop(self) -> AbstractEventLoop: ...
    def set_child_watcher(self, watcher: AbstractChildWatcher) -> None: ...
    def set_event_loop(self, loop: AbstractEventLoop | None) -> None: ...
