"""Add lowercase phrase text

Revision ID: 0e84cb2e50d0
Revises: 23d2bda70fdb
Create Date: 2026-09-11 14:22:41.609126

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import bindparam, column, func, literal, select, table, update

# revision identifiers, used by Alembic.
revision: str = "0e84cb2e50d0"
down_revision: str | Sequence[str] | None = "23d2bda70fdb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "phrase",
        sa.Column(
            "text_lower", sa.String(), nullable=False, server_default=literal("")
        ),
    )
    op.create_index(
        op.f("ix_phrase_text_lower"), "phrase", ["text_lower"], unique=False
    )
    # ### end Alembic commands ###

    # Update text_lower column with correct values
    connection = op.get_context().connection
    if not connection:
        raise ValueError("Need connection to upgrade")
    phrase_table = table("phrase", column("id"), column("text"), column("text_lower"))
    last_id = 0
    phrase_count = connection.scalar(func.count(phrase_table.c["id"]))

    print(f"Updating {phrase_count} phrase records to have valid text_lower...")
    while True:
        rows = connection.execute(
            select(phrase_table.c["id"], phrase_table.c["text"])
            .where(phrase_table.c["id"] > last_id)
            .order_by(column("id").asc())
            .limit(1000)
        ).all()
        params = [{"phrase_id": row.id, "text_lower": row.text.lower()} for row in rows]
        if not params:
            break
        last_id = max(prm["phrase_id"] for prm in params)

        connection.execute(
            update(phrase_table)
            .where(phrase_table.c["id"] == bindparam("phrase_id"))
            .values(text_lower=bindparam("text_lower")),
            params,
        )
    print("Phrase records are updated")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_phrase_text_lower"), table_name="phrase")
    op.drop_column("phrase", "text_lower")
    # ### end Alembic commands ###
