"""Initial

Revision ID: 23d2bda70fdb
Revises: 
Create Date: 2025-08-20 13:50:11.164007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d2bda70fdb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phrase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phrase_text'), 'phrase', ['text'], unique=True)
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase_id', sa.Integer(), nullable=False),
    sa.Column('dictionary_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('dtype', sa.Enum('TEXT', 'XDXF', name='articleformat'), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionary.id'], ),
    sa.ForeignKeyConstraint(['phrase_id'], ['phrase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_phrase_id'), 'article', ['phrase_id'], unique=False)
    op.create_table('view_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase_id', sa.Integer(), nullable=False),
    sa.Column('shown_at_utc', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['phrase_id'], ['phrase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_view_log_phrase_id'), 'view_log', ['phrase_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_view_log_phrase_id'), table_name='view_log')
    op.drop_table('view_log')
    op.drop_index(op.f('ix_article_phrase_id'), table_name='article')
    op.drop_table('article')
    op.drop_index(op.f('ix_phrase_text'), table_name='phrase')
    op.drop_table('phrase')
    op.drop_table('dictionary')
    # ### end Alembic commands ###
